# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACMS', '0003_patient'),
    ]

    operations = [
    ]
