# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACMS', '0003_auto_20160731_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmo_list',
            name='email',
            field=models.EmailField(default='no email', help_text='Please enter a valid email address!', max_length=254),
        ),
    ]
