# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 01:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ACMS', '0004_merge_20160824_0115'),
    ]

    operations = [

        migrations.CreateModel(
            name='drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=50)),
                ('drug_code', models.CharField(max_length=15)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                               to=settings.AUTH_USER_MODEL)),
            ],
        ),

        migrations.AlterField(
            model_name='patient',
            name='origin',
            field=models.CharField(default='NIL', max_length=10, null=True),
        ),
    ]
