# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 01:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ACMS', '0004_merge_20160824_0115'),
    ]

    operations = [

        migrations.AlterField(
            model_name='patient',
            name='origin',
            field=models.CharField(default='NIL', max_length=10, null=True),
        ),
    ]
