# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ACMS', '0005_auto_20160731_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('card_no', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=1)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='hmo_list',
            name='hmo_status',
            field=models.BooleanField(default='0', help_text='uncheck if HMO is not active', verbose_name='Hmo Status'),
        ),
        migrations.AddField(
            model_name='patients',
            name='hmo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ACMS.hmo_list'),
        ),
    ]
