# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 22:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ACMS', '0005_auto_20160824_0206'),
    ]

    operations = [

        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=15, verbose_name='State')),
            ],
        ),
        migrations.AddField(
            model_name='hmo_list',
            name='added_by',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hmo_list',
            name='address',
            field=models.TextField(default='NIL'),
        ),
        migrations.AddField(
            model_name='hmo_list',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hmo_list',
            name='email',
            field=models.EmailField(blank=True, default='no-email@domain.com', help_text='Please enter a valid email address!', max_length=254),
        ),
        migrations.AddField(
            model_name='hmo_list',
            name='hmo_status',
            field=models.BooleanField(default='0', help_text='uncheck if HMO is not active', verbose_name='Hmo Status'),
        ),
        migrations.AlterField(
            model_name='hmo_list',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
