# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ACMS', '0006_auto_20160822_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('card_no', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('hmo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ACMS.hmo_list')),
            ],
        ),
        migrations.RemoveField(
            model_name='patients',
            name='hmo_id',
        ),
        migrations.DeleteModel(
            name='patients',
        ),
    ]
