# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACMS', '0006_auto_20160915_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='state_name',
            new_name='name',
        ),
    ]
