# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ACMS', '0007_auto_20160822_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
