# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ACMS', '0009_auto_20160822_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='hmo',
        ),
        migrations.AddField(
            model_name='patient',
            name='hmo_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ACMS.hmo_list', verbose_name='hmo_id'),
        ),
    ]
