# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 23:41
from __future__ import unicode_literals
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACMS', '0011_auto_20160916_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='State')),
            ],
        ),

    ]
