# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ACMS', '0011_auto_20160925_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='druggers',
            name='added_by',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='hmo_id',
            new_name='hmo',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='othername',
            new_name='othernames',
        ),
        migrations.AlterField(
            model_name='drug',
            name='added_by',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hmo_list',
            name='added_by',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='added_by',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='origin',
            field=models.ForeignKey(default=38, on_delete=django.db.models.deletion.CASCADE, to='ACMS.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_name',
            field=models.CharField(max_length=15, verbose_name='Name of State'),
        ),
        migrations.DeleteModel(
            name='druggers',
        ),
    ]
