# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACMS', '0012_auto_20160916_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='name',
            new_name='state_name',
        ),
    ]
