# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACMS', '0012_drug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmo_list',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
