# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ACMS', '0013_auto_20160916_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='origin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ACMS.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_name',
            field=models.CharField(max_length=15, verbose_name='Name of State'),
        ),
    ]
