# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACMS', '0013_druggers'),
        ('ACMS', '0012_auto_20160925_2018'),
    ]

    operations = [
    ]
