# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACMS', '0015_druggers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='druggers',
            name='added_by',
        ),
        migrations.DeleteModel(
            name='druggers',
        ),
    ]
