/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hdms;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Window;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author koyexes
 */
public class MainContainer extends javax.swing.JFrame {

    /**
     * Creates new form MainJframe
     */
    public MainContainer() {
        initComponents();
        //add(new ImagePanel(super.getWidth(),super.getHeight()), BorderLayout.CENTER
        add(jPanel1, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hdms/images/medgirl.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        Graphics g = jPanel1.getGraphics();
        g.drawImage(image, 0, 0, 500, 700,this );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("HMO DATA MANAGEMENT SYSTEM");
        setMinimumSize(new java.awt.Dimension(700, 500));
        setName("mainContainer"); // NOI18N
        setSize(new java.awt.Dimension(700, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                mainContainerWindowClosing(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainContainerWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_mainContainerWindowClosing
        int optionChosen = JOptionPane.showConfirmDialog(this, "LOGOUT: ARE YOU SURE?", "Logout " + LoginPage.getFullName(), JOptionPane.YES_NO_OPTION, 
                                                           JOptionPane.QUESTION_MESSAGE);
        if(optionChosen == JOptionPane.YES_OPTION){
            if(Processes.logout()){
                this.dispose();
                for(Window win : Window.getWindows()){
                    if(win.getName().equalsIgnoreCase("loginFrame")){
                        win.setVisible(true);
                    }
                }
            }else{
                int exitOption = JOptionPane.showConfirmDialog(this, "EXIT BY FORCE?", "Logout Error", JOptionPane.YES_NO_OPTION, 
                                                                    JOptionPane.ERROR_MESSAGE);
                if(exitOption == JOptionPane.YES_OPTION){
                    System.exit(0);
                }
            }
        }
        
    }//GEN-LAST:event_mainContainerWindowClosing

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainContainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainContainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainContainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainContainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainContainer().setVisible(true);
            }
        });
    }
    ImageIcon backgroundImagecon = new ImageIcon(getClass().getResource("/hdms/images/medgirl.jpg"));
    Image image = backgroundImagecon.getImage();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
 /*class ImagePanel extends JPanel{

    public ImagePanel(int width, int height) {
       imageWidth = width;
       imageHeight = height;
    }
    int imageWidth, imageHeight;
    ImageIcon backgroundImagecon = new ImageIcon(getClass().getResource("/hdms/images/medgirl.jpg"));
    Image image = backgroundImagecon.getImage();


    @Override
    protected void paintComponent(Graphics g){
       super.paintComponent(g);
       System.out.println(image);
       if(image != null){
        g.drawImage(image, 0, 0,imageWidth,imageHeight, this);
       }else{
           System.err.println("error");
       }

    }
}*/


